spring.application.name=jahinventory

spring.datasource.url=jdbc:mysql://localhost:3306/inventory
spring.datasource.username=nurali
spring.datasource.password=java1973

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
